In [3]:
import pandas as pd

In [4]:
s=pd.Series([10,20,30,40])

In [5]:
print(s)

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
data={'maths':90,
      'physics':'85',
      'chemistry':'88'
     }
s=pd.Series(data)
print(s)

maths        90
physics      85
chemistry    88
dtype: object

In [7]:
s=pd.Series([10,20,30,40])
print(s[0])

10

In [8]:
s=pd.Series([100,200,300],
            index=['a','b','c'])
print(s['b'])

200

In [9]:
print(s.shape)

(3,)

In [10]:
print(s.size)

3

In [11]:
print(s.dtype)

int64

In [12]:
s=pd.Series([10,20,30,40])
print(s+10)

0    20
1    30
2    40
3    50
dtype: int64

In [13]:
print('sum=',s.sum())
print('mean=',s.mean())
print('maximum=',s.max())
print('minimum=',s.min())

sum= 100
mean= 25.0
maximum= 40
minimum= 10

In [14]:
data={'RollNo':[101,102,103],
      'name':['Arun','Priya','Rahul'],
      'Marks':[85,90,78]
     }
df=pd.DataFrame(data)
print(df)

   RollNo   name  Marks
0     101   Arun     85
1     102  Priya     90
2     103  Rahul     78

In [15]:
df=pd.DataFrame(data, 
                index=['a','b','c'])         
print(df)

   RollNo   name  Marks
a     101   Arun     85
b     102  Priya     90
c     103  Rahul     78

In [16]:
print(df.columns)

Index(['RollNo', 'name', 'Marks'], dtype='object')

In [17]:
print(df.index)

Index(['a', 'b', 'c'], dtype='object')

In [18]:
print(df.dtypes)

RollNo     int64
name      object
Marks      int64
dtype: object

In [19]:
print(df['name'])

a     Arun
b    Priya
c    Rahul
Name: name, dtype: object

In [20]:
print(df[['name','Marks']])

    name  Marks
a   Arun     85
b  Priya     90
c  Rahul     78

In [21]:
print(df.loc['a'])

RollNo     101
name      Arun
Marks       85
Name: a, dtype: object

In [22]:
print(df.loc['b'])

RollNo      102
name      Priya
Marks        90
Name: b, dtype: object

In [23]:
print(df.loc[['a','c']])

   RollNo   name  Marks
a     101   Arun     85
c     103  Rahul     78

In [24]:
df['grade']=['A','A+','B']
print(df)

   RollNo   name  Marks grade
a     101   Arun     85     A
b     102  Priya     90    A+
c     103  Rahul     78     B

In [25]:
df['Marks']=df['Marks']+5
print(df)

   RollNo   name  Marks grade
a     101   Arun     90     A
b     102  Priya     95    A+
c     103  Rahul     83     B

In [26]:
df.drop('grade',
        axis=1,
        inplace=True)

In [27]:
print(df)

   RollNo   name  Marks
a     101   Arun     90
b     102  Priya     95
c     103  Rahul     83

In [28]:
print(df['Marks'].sum())

268

In [29]:
print(df['Marks'].mean())

89.33333333333333

In [37]:
print(df['Marks'].max())

95

In [38]:
df.sort_values("Marks")

   RollNo   name  Marks
c     103  Rahul     83
a     101   Arun     90
b     102  Priya     95

In [39]:

print(df[df["Marks"]<90])

   RollNo   name  Marks
c     103  Rahul     83

In [41]:

df.sort_values("Marks",ascending=true)

NameError: name 'true' is not defined

In [45]:

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, a to c
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RollNo  3 non-null      int64
 1   name    3 non-null      object
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes

In [43]:
df.head()

   RollNo   name  Marks
a     101   Arun     90
b     102  Priya     95
c     103  Rahul     83

In [44]:
df.tail()

   RollNo   name  Marks
a     101   Arun     90
b     102  Priya     95
c     103  Rahul     83

In [46]:
df.describe()

       RollNo      Marks
count     3.0   3.000000
mean    102.0  89.333333
std       1.0   6.027714
min     101.0  83.000000
25%     101.5  86.500000
50%     102.0  90.000000
75%     102.5  92.500000
max     103.0  95.000000

In [49]:
import pandas as pd
data={
    'roll no':[101,102,103,104,105,106,107],
    'name':['rishika','nethra','deepika','ajay','zion','vithya','ashvanth'],
    'department':['cs','ai','ds','dv','maths','physics','chem'],
    'marks':[96,88,90,83,77,99,98]
}
df=pd.DataFrame(data)
print(df)

   roll no      name department  marks
0      101   rishika         cs     96
1      102    nethra         ai     88
2      103   deepika         ds     90
3      104      ajay         dv     83
4      105      zion      maths     77
5      106    vithya    physics     99
6      107  ashvanth       chem     98

In [51]:
print(df['marks'].sum())

631

In [52]:
print(df['marks'].mean())

90.14285714285714

In [ ]:
print(df['Marks'].sum())